export const LOAD_ATIVOS_DISPONIVEIS = "LOAD_ATIVOS_DISPONIVEIS";
export const LOAD_BEBIDAS_DISPONIVEIS = "LOAD_BEBIDAS_DISPONIVEIS";
export const LOAD_CLIENTES_ENDERECOS = "LOAD_CLIENTES_ENDERECOS";
export const LOAD_CONFIGURACOES_PADRAO = "LOAD_CONFIGURACOES_PADRAO";

export const CHANGE_MAQUINA = "CHANGE_MAQUINA";
export const CHANGE_PAG_TIPO = "CHANGE_PAG_TIPO";
export const CHANGE_VALIDADOR_TIPO = "CHANGE_VALIDADOR_TIPO";
export const CHANGE_VALIDADOR_FICHAS = "CHANGE_VALIDADOR_FICHAS";

export const CLICK_ADD_BEBIDA = "CLICK_ADD_BEBIDA";
export const CLICK_REMOVE_BEBIDA = "CLICK_REMOVE_BEBIDA";
export const CLEAR_CONFIG = "CLEAR_CONFIG";

export const CHANGE_MAQUINA_CORPORATIVA = "CHANGE_MAQUINA_CORPORATIVA";
export const CHOOSE_INIBIR_COPOS = "CHOOSE_INIBIR_COPOS";
export const CHOOSE_ACOMPANHA_GABINETE = "CHOOSE_ACOMPANHA_GABINETE";
export const CHOOSE_ABASTECIMENTO_HIDRICO = "CHOOSE_ABASTECIMENTO_HIDRICO";
export const CHOOSE_CHIP_TELEMETRIA = "CHOOSE_CHIP_TELEMETRIA";
export const CHOOSE_ANTENA_EXTERNA = "CHOOSE_ANTENA_EXTERNA";

export const CHOOSE_CLIENTE = "CHOOSE_CLIENTE";
export const CHANGE_ENDERECO = "CHANGE_ENDERECO";
export const DATA_ENTREGA_DESEJADA = "DATA_ENTREGA_DESEJADA";
export const CHOOSE_CONTATO = "CHOOSE_CONTATO";
export const CHOOSE_EMAIL_ACOMPANHAMENTO = "CHOOSE_EMAIL_ACOMPANHAMENTO";
export const CHOOSE_TELEFONE_CONTATO = "CHOOSE_TELEFONE_CONTATO";
export const SET_OBSERVACAO = "SET_OBSERVACAO";

