export const LOAD_LEADS_FRANQUEADO = "LOAD_LEADS_FRANQUEADO";
export const LOAD_LEADS_GERAL = "LOAD_LEADS_GERAL";
export const LOAD_LEADS_LIMITE = "LOAD_LEADS_LIMITE";

export const ADD_LIMITE = 'ADD_LIMITE'
export const SUB_LIMITE = 'SUB_LIMITE'

export const MOVE_LEAD = 'MOVE_LEAD'
export const UPD_LEAD = 'UPD_LEAD'