export const REACT_APP_FRANQUEADO_ROLE_LEVEL = "1";
export const REACT_APP_TECNICA_ROLE_LEVEL = "2";
export const REACT_APP_EXPEDICAO_ROLE_LEVEL = "3";
export const REACT_APP_JURIDICO_ROLE_LEVEL = "4";
export const REACT_APP_BACKOFFICE_ROLE_LEVEL = "5";
export const REACT_APP_SISTEMA_ROLE_LEVEL = "6";
